#!/usr/bin/env zsh

print "Usage:
  zman [subcommand] [plugin]

Subcommands:
  help        Print this menu
  load        Optionally install and load the provided plugin
  list        List all installed plugins
  update      When no plugin is provided, update Zman itself, else
              update the corresponding plugin. The special plugin name \"all\"
              will trigger the update of all installed plugins
  purge       When no plugin is provided, Zman will uninstall all of
              the installed plugins that are not loaded, else it will
              only uninstall the provided plugin
"

