#!/usr/bin/env zsh

0=${(%):-%x}

fpath=( "${0:A:h}" $fpath)

local fn
for fn in ${0:A:h}/*(N); do
    # Don't autoload the setup function again
    [[ ${fn:t} == "_zman_setup" ]] && continue || builtin autoload -Uz ${fn}
done

# Allow the user to configure a custom ZMAN_PLUGINS path
if [[ -z $ZMAN_PLUGINS ]]; then
    # Default to a somewhat logical path
    typeset -gx ZMAN_PLUGINS
    ZMAN_PLUGINS="${XDG_DATA_HOME:-$HOME/.local/share}/zman/plugins"
fi

