#!/usr/bin/env zsh

0=${(%):-%x}

case $1 in
    help | list)
        _zman_$1
        ;;

    load)
        ;;

    update)
        ;;

    *)
        _zman_print "Unknown action \"$1\""
        ;;
esac
